# Generated by Django 3.2.6 on 2025-03-17 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrd', '0003_auto_20250304_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id_rules', models.AutoField(primary_key=True, serialize=False)),
                ('nama_rule', models.CharField(max_length=100)),
                ('jam_masuk', models.TimeField()),
                ('jam_keluar', models.TimeField()),
                ('toleransi_telat', models.IntegerField(default=15, help_text='Toleransi keterlambatan dalam menit')),
                ('maksimal_izin', models.IntegerField(default=3, help_text='Jumlah maksimal izin dalam sebulan')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id_absensi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('bulan', models.IntegerField()),
                ('tahun', models.IntegerField()),
                ('status_absensi', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Libur', 'Libur')], max_length=20)),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_keluar', models.TimeField(blank=True, null=True)),
                ('is_libur', models.BooleanField(default=False)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd.karyawan')),
            ],
        ),
    ]
