# Generated by Django 3.2.6 on 2025-03-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='nama_rule',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
