# Generated by Django 3.2.6 on 2025-03-20 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0003_absensi_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absensi',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='absensi',
            name='nama_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='status_absensi',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Libur', 'Libur')], max_length=20),
        ),
    ]
