# Generated by Django 3.2.6 on 2025-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_alter_absensi_status_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status_absensi',
            field=models.CharField(choices=[('Tepat Waktu', 'Tepat Waktu'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Cuti', 'Cuti'), ('Libur', 'Libur')], max_length=20),
        ),
    ]
