# Generated by Django 3.2.6 on 2025-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0006_alter_absensi_status_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status_absensi',
            field=models.CharField(choices=[('Tepat Waktu', 'Tepat Waktu'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Cuti', 'Cuti'), ('Libur', 'Libur'), ('Research and Innovation', 'Research and Innovation'), ('CPEBR', 'CPEBR')], max_length=25),
        ),
    ]
