# Generated by Django 3.2.6 on 2025-03-04 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('divisi', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('role', models.CharField(choices=[('Karyawan Tetap', 'Karyawan Tetap'), ('Magang', 'Magang'), ('HRD', 'HRD')], max_length=20)),
                ('status', models.CharField(choices=[('Belum kawin', 'Belum kawin'), ('Kawin', 'Kawin'), ('Cerai hidup', 'Cerai hidup'), ('Cerai mati', 'Cerai mati')], max_length=20)),
                ('mulai_kontrak', models.DateField(blank=True, null=True)),
                ('batas_kontrak', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'karyawan',
            },
        ),
    ]
