# Generated by Django 3.2.6 on 2025-03-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='role',
        ),
    ]
