# Generated by Django 3.2.6 on 2025-03-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0002_remove_karyawan_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='status_keaktifan',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15),
        ),
    ]
