# Generated by Django 3.2.6 on 2025-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0003_auto_20250304_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='nama_catatan_kehadiran',
            field=models.CharField(blank=True, help_text='Nama yang digunakan dalam catatan kehadiran', max_length=100, null=True),
        ),
    ]
