# Generated by Django 3.2.6 on 2025-03-26 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0004_auto_20250320_0928'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrd', '0004_karyawan_nama_catatan_kehadiran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('tanggal_izin', models.DateField()),
                ('jenis_izin', models.CharField(choices=[('menikah', 'Izin Menikah'), ('berkabung', 'Izin Berkabung'), ('khitan', 'Izin Mengkhitankan Anak'), ('baptis', 'Izin Baptis Anak'), ('istri_melahirkan', 'Izin Istri Melahirkan/Keguguran'), ('wfh', 'Izin WFH')], max_length=50)),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('file_pengajuan', models.FileField(blank=True, null=True, upload_to='izin/file_pengajuan/')),
                ('file_persetujuan', models.FileField(blank=True, null=True, upload_to='izin/file_persetujuan/')),
                ('absensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.absensi')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_izin', to=settings.AUTH_USER_MODEL)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd.karyawan')),
            ],
            options={
                'db_table': 'izin',
            },
        ),
        migrations.CreateModel(
            name='Cuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('jenis_cuti', models.CharField(choices=[('tahunan', 'Cuti Tahunan'), ('bersama', 'Cuti Bersama'), ('melahirkan', 'Cuti Melahirkan'), ('menikah', 'Cuti Menikah'), ('menikahkan', 'Cuti Menikahkan Anak'), ('berkabung', 'Cuti Berkabung'), ('khitan', 'Cuti Khitan Anak'), ('baptis', 'Cuti Baptis Anak'), ('istri_melahirkan', 'Cuti Istri Melahirkan/Keguguran'), ('sakit', 'Cuti Sakit')], max_length=50)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('file_pengajuan', models.FileField(blank=True, null=True, upload_to='cuti/file_pengajuan/')),
                ('file_persetujuan', models.FileField(blank=True, null=True, upload_to='cuti/file_persetujuan/')),
                ('absensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='absensi.absensi')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_cuti', to=settings.AUTH_USER_MODEL)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd.karyawan')),
            ],
            options={
                'db_table': 'cuti',
            },
        ),
    ]
