# Generated by Django 3.2.6 on 2025-04-08 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0005_cuti_izin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutiBersama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cuti_bersama',
                'unique_together': {('tanggal',)},
            },
        ),
        migrations.CreateModel(
            name='JatahCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('total_cuti', models.IntegerField(default=12)),
                ('sisa_cuti', models.IntegerField(default=12)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd.karyawan')),
            ],
            options={
                'db_table': 'jatah_cuti',
                'unique_together': {('karyawan', 'tahun')},
            },
        ),
    ]
