# Generated by Django 3.2.6 on 2025-04-08 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrd', '0006_cutibersama_jatahcuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='TidakAmbilCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_awal', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('file_pengajuan', models.FileField(blank=True, null=True, upload_to='tidak_ambil_cuti/file_pengajuan/')),
                ('file_persetujuan', models.FileField(blank=True, null=True, upload_to='tidak_ambil_cuti/file_persetujuan/')),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tidak_ambil_cuti', to=settings.AUTH_USER_MODEL)),
                ('id_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrd.karyawan')),
            ],
            options={
                'db_table': 'tidak_ambil_cuti',
            },
        ),
    ]
