# Generated by Django 3.2.6 on 2025-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0007_tidakambilcuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuti',
            name='file_dokumen_formal',
            field=models.FileField(blank=True, help_text='File .docx cuti yang ditandatangani', null=True, upload_to='cuti/file_dokumen_formal/'),
        ),
    ]
