# Generated by Django 3.2.6 on 2025-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0008_cuti_file_dokumen_formal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izin',
            name='jenis_izin',
            field=models.CharField(choices=[('telat', 'Izin Telat'), ('wfh', 'Izin WFH')], max_length=50),
        ),
    ]
