# Generated by Django 3.2.6 on 2025-04-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0009_alter_izin_jenis_izin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tidakambilcuti',
            name='tanggal_akhir',
        ),
        migrations.RemoveField(
            model_name='tidakambilcuti',
            name='tanggal_awal',
        ),
        migrations.AddField(
            model_name='tidakambilcuti',
            name='tanggal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
