# Generated by Django 3.2.6 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0010_auto_20250410_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tidakambilcuti',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='tidakambilcuti',
            name='tanggal',
            field=models.ManyToManyField(blank=True, to='hrd.CutiBersama'),
        ),
    ]
