# Generated by Django 3.2.6 on 2025-04-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrd', '0011_auto_20250410_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to=settings.AUTH_USER_MODEL),
        ),
    ]
