# Generated by Django 3.2.6 on 2025-04-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0012_alter_karyawan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuti',
            name='feedback_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='izin',
            name='feedback_hr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuti',
            name='jenis_cuti',
            field=models.CharField(choices=[('tahunan', 'Cuti Tahunan'), ('melahirkan', 'Cuti Melahirkan'), ('menikah', 'Cuti Menikah'), ('menikahkan', 'Cuti Menikahkan Anak'), ('berkabung', 'Cuti Berkabung'), ('khitan', 'Cuti Khitan Anak'), ('baptis', 'Cuti Baptis Anak'), ('istri_melahirkan', 'Cuti Istri Melahirkan/Keguguran'), ('sakit', 'Cuti Sakit')], max_length=50),
        ),
    ]
