# Generated by Django 3.2.6 on 2025-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0013_auto_20250421_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='tidakambilcuti',
            name='feedback_hr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
