# Generated by Django 3.2.6 on 2025-05-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0015_auto_20250430_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailJatahCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('bulan', models.IntegerField()),
                ('dipakai', models.BooleanField(default=False)),
                ('jumlah_hari', models.IntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
                ('jatah_cuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='hrd.jatahcuti')),
            ],
            options={
                'db_table': 'detail_jatah_cuti',
                'ordering': ['tahun', 'bulan'],
                'unique_together': {('jatah_cuti', 'tahun', 'bulan')},
            },
        ),
    ]
