# Generated by Django 3.2.6 on 2025-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0016_detailjatahcuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='divisi',
            field=models.CharField(choices=[('General', 'General'), ('DART', 'DART'), ('Annotation', 'Annotation'), ('Rinov', 'Rinov'), ('Basic Research', 'Basic Research'), ('Dataset', 'Dataset'), ('Media Dataset', 'Media Dataset'), ('Media Non Dataset', 'Media Non Dataset'), ('Consulting', 'Consulting')], max_length=50),
        ),
    ]
