# Generated by Django 3.2.6 on 2025-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0017_alter_karyawan_divisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
