# Generated by Django 3.2.6 on 2025-05-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0018_karyawan_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
