# Generated by Django 3.2.6 on 2025-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0019_karyawan_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='divisi',
            field=models.CharField(choices=[('General', 'General'), ('DART', 'DART'), ('Annotation', 'Annotation'), ('Research and Innovation', 'Research and Innovation'), ('CPEBR', 'CPEBR'), ('Dataset', 'Dataset'), ('Media Dataset', 'Media Dataset'), ('Media Non Dataset', 'Media Non Dataset'), ('Consulting', 'Consulting')], max_length=50),
        ),
    ]
